# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: doc/mkdocs.yml

python:
  install:
    # Added this to fix an MkDocs error about `site_dir`
    # https://github.com/readthedocs/readthedocs.org/issues/4974#issuecomment-735320443
    - requirements: doc/requirements.txt
