// Generated file

// clang-format off
const char *g_detail_modifier_shader_template_0 = 
"#version 450\n"
"\n"
"// Takes a list of positions and evaluates a signed distance field in 4 locations around them.\n"
"// The 4 locations are picked such that the result can be used to compute a gradient.\n"
"// The result is then applied on top of previous values using a specified operation.\n"
"\n"
"// This shader may be dispatched multiple times for each source of voxel data that we may combine for a given chunk.\n"
"\n"
"layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;\n"
"\n"
"layout (set = 0, binding = 0, std430) restrict buffer PositionBuffer {\n"
"	// X, Y, Z is hit position\n"
"	// W is integer triangle index\n"
"	vec4 values[];\n"
"} u_positions;\n"
"\n"
"layout (set = 0, binding = 1, std430) restrict buffer Params {\n"
"	int tile_size_pixels;\n"
"	float pixel_world_step;\n"
"	int operation;\n"
"} u_params;\n"
"\n"
"layout (set = 0, binding = 2, std430) restrict buffer InSDBuffer {\n"
"	// 4 values per index\n"
"	float values[];\n"
"} u_in_sd;\n"
"\n"
"layout (set = 0, binding = 3, std430) restrict buffer OutSDBuffer {\n"
"	// 4 values per index\n"
"	float values[];\n"
"} u_out_sd;\n"
"\n";
// clang-format on

// clang-format off
const char *g_detail_modifier_shader_template_1 = 
"\n"
"void main() {\n"
"	const ivec2 pixel_pos_in_tile = ivec2(gl_GlobalInvocationID.xy);\n"
"	const int tile_index = int(gl_GlobalInvocationID.z);\n"
"\n"
"	const int index = pixel_pos_in_tile.x + pixel_pos_in_tile.y * u_params.tile_size_pixels \n"
"		+ tile_index * u_params.tile_size_pixels * u_params.tile_size_pixels;\n"
"\n"
"	if (u_positions.values[index].w == -1.0) {\n"
"		return;\n"
"	}\n"
"\n"
"	const vec3 pos0 = u_positions.values[index].xyz;\n"
"	const vec3 pos1 = pos0 + vec3(u_params.pixel_world_step, 0.0, 0.0);\n"
"	const vec3 pos2 = pos0 + vec3(0.0, u_params.pixel_world_step, 0.0);\n"
"	const vec3 pos3 = pos0 + vec3(0.0, 0.0, u_params.pixel_world_step);\n"
"\n"
"	const int sdi = index * 4;\n"
"\n"
"	float sd0 = u_in_sd.values[sdi];\n"
"	float sd1 = u_in_sd.values[sdi + 1];\n"
"	float sd2 = u_in_sd.values[sdi + 2];\n"
"	float sd3 = u_in_sd.values[sdi + 3];\n"
"\n"
"	const float msd0 = get_sd(pos0);\n"
"	const float msd1 = get_sd(pos1);\n"
"	const float msd2 = get_sd(pos2);\n"
"	const float msd3 = get_sd(pos3);\n"
"\n"
"	if (u_params.operation == 0) {\n"
"		// Union\n"
"		sd0 = min(msd0, sd0);\n"
"		sd1 = min(msd1, sd1);\n"
"		sd2 = min(msd2, sd2);\n"
"		sd3 = min(msd3, sd3);\n"
"\n"
"	} else if (u_params.operation == 1) {\n"
"		// Subtract\n"
"		sd0 = max(msd0, -sd0);\n"
"		sd1 = max(msd1, -sd1);\n"
"		sd2 = max(msd2, -sd2);\n"
"		sd3 = max(msd3, -sd3);\n"
"\n"
"	} else {\n"
"		sd0 = msd0;\n"
"		sd1 = msd1;\n"
"		sd2 = msd2;\n"
"		sd3 = msd3;\n"
"	}\n"
"\n"
"	u_out_sd.values[sdi] = sd0;\n"
"	u_out_sd.values[sdi + 1] = sd1;\n"
"	u_out_sd.values[sdi + 2] = sd2;\n"
"	u_out_sd.values[sdi + 3] = sd3;\n"
"}\n"
"\n";
// clang-format on
